global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend FastAPI avec métriques
  - job_name: 'dockezr-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Base de données PostgreSQL (via postgres_exporter si ajouté)
  - job_name: 'dockezr-database'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 30s

  # Frontend Next.js (métriques de base)
  - job_name: 'dockezr-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s

  # Node Exporter pour métriques système (optionnel)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
