global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'dockezr-prod'
    environment: 'production'

rule_files:
  # - "dockezr_rules.yml"

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Backend FastAPI avec métriques personnalisées
  - job_name: 'dockezr-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Node Exporter pour métriques système du serveur
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['141.253.118.141:9100']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Base de données PostgreSQL (pour monitoring futur)
  - job_name: 'dockezr-database'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 60s
    scrape_timeout: 10s

  # Frontend Next.js (pour monitoring futur)
  - job_name: 'dockezr-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 60s
    scrape_timeout: 10s
